[[plugins]]
repo = 'google/vim-jsonnet'
on_ft = ['jsonnet', 'libsonnet']

[[plugins]]
repo = 'arrufat/vala.vim'
on_ft = ['vala']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'evanleck/vim-svelte'
on_ft = ['svelte']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_add = '''
    let g:markdown_syntax_conceal = 0
    let g:markdown_fenced_languages = [
    \ 'html', 'css', 'javascript', 'typescript', 'python', 'go', 'rust',
    \ 'c', 'cpp', 'java', 'vim', 'tex', 'lua', 'make', 'dockerfile',
    \ 'bash=sh', 'json', 'yaml', 'toml',
    \ ]
'''

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'alaviss/nim.nvim'
on_ft = ['nim', 'nimble']

[[plugins]]
repo = 'altescy/hush.vim'
on_ft = ['hush']

[[plugins]]
repo = 'ziglang/zig.vim'
on_ft = ['zig']

[[plugins]]
repo = 'vim-crystal/vim-crystal'
on_ft = ['crystal']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
