[[plugins]]
repo = 'google/vim-jsonnet'
on_ft = ['jsonnet', 'libsonnet']

[[plugins]]
repo = 'arrufat/vala.vim'
on_ft = ['vala']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'evanleck/vim-svelte'
on_ft = ['svelte']

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = ['md']
