name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl file git locales locales-all
        sudo locale-gen ja_JP.UTF-8
        sudo update-locale
    - name: Install linuxbrew
      run: |
        make brew
        eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    - name: Setup applications
      run: |
        eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        make apps languages configs
